src/blog/urls.py
""" URLs for the blog app """

from django.conf.urls import url

from . import views

__author__ = 'Alamgir Kabir Roni, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.blog_list,
        name='blog_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.blog_detail,
        name='blog_detail'
    ),
]

src/contact/urls.py
""" URLs for the contact app """

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

__author__ = 'Sathi'
__copyright__ = 'Copyright 2018, Maison Mahdil'


urlpatterns = [

    # Forms
    url(
        r'^contactform/$',
        views.contact_form,
        name='contactform'
    ),
    url(
        r'^newsletter/$',
        views.newsletter_form,
        name='newsletter'
    ),

    # Email
    url(
        r'^confirmation_mail/$',
        TemplateView.as_view(
            template_name='contact/email/confirmation_mail.html'
        )
    ),
    url(
        r'^customer_confirmation_mail/$',
        TemplateView.as_view(
            template_name='contact/email/customer_confirmation_mail.html'
        )
    ),
]

src/mahdil/urls.py
""" mahdil URL Configuration """

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from mahdil.sitemaps import main_sitemaps

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = i18n_patterns(

    # Admin
    url(
        r'^admin/',
        include(admin.site.urls)
    ),

    # Third party apps URLs
    url(
        r'^accounts/',
        include('allauth.urls')
    ),
    url(
        r'^ckeditor/',
        include('ckeditor_uploader.urls')
    ),

    # Pages
    url(
        r'^',
        include('page.urls', namespace='page')
    ),
    url(
        r'^blog/',
        include('blog.urls', namespace='blog')
    ),
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),
    url(
        r'^eshop/',  # Linked to external payment module
        include('eshop.urls', namespace='eshop')
    ),
    url(
        r'^my-caps/',
        include('mycaps.urls', namespace='mycaps')
    ),
    url(
        r'^capsule-compatible-nespresso/',
        include('product.urls', namespace='product')
    ),
    url(
        r'^produits/',
        include('product.urls', namespace='product-others')
    ),
    url(
        r'^profil/',
        include('userprofile.urls', namespace='userprofile')
    ),
    url(
        r'^main/',
        include('main.urls', namespace='main')
    ),

    # API
    url(
        r'^api/main/',
        include('main.api.urls', namespace='main_api')
    ),
    url(
        r'^api/product/',
        include('product.api.urls', namespace='product_api')
    ),
    url(
        r'^api/page/',
        include('page.api.urls', namespace='page_api')
    ),

    # Sitemap,
    url(
        r'^sitemap\.xml$',
        sitemap, {'sitemaps': main_sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

urlpatterns += [

    # Robots,
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='main/robots.txt')
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/contact/models.py
""" Models for the contact app """

from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _


# Models
class Contact(models.Model):

    # Attributes
    name = models.CharField(
        _('name'),
        max_length=120,
    )
    email = models.EmailField(
        _('email'),
    )
    message = models.TextField(
        _('message'),
    )

    # Meta Data
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        editable=False,
        null=True,
    )

    # Functions
    def __str__(self):
        return "%s" % (self.name)

    def __unicode__(self):
        return u"%s" % (self.name)

    # Meta
    class Meta:
        ordering = ['-created_on']
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

src/contact/forms.py
""" Forms for the contact app """

from django import forms

from . import models

__author__ = 'Sathi, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Forms
class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact

        fields = [
            'name',
            'email',
            'message',
        ]


class NewsletterForm(forms.Form):
    email_address = forms.EmailField()

src/contact/views.py
""" Views for the contact app """

import json
import mailchimp

from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from main.models import Text

from . import forms

__author__ = 'Sathi'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Views
def contact_form(request):
    if request.method == 'POST':
        form = forms.ContactForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            text_list = Text.objects.all()
            instance.save()
            ctx = {
                'instance': instance,
                'text_list': text_list,
            }
            msg_plain = render_to_string(
                'contact/email/confirmation_mail.txt',
                ctx
            )
            msg_html = render_to_string(
                'contact/email/confirmation_mail.html',
                ctx
            )
            subject = _('Subject')
            message = msg_plain
            from_email = settings.EMAIL_HOST_USER
            to_list = [settings.ADMIN]
            send_mail(
                subject,
                message,
                from_email,
                to_list,
                html_message=msg_html,
                fail_silently=True
            )
            customer_msg_plain = render_to_string(
                'contact/email/customer_confirmation_mail.txt',
                ctx
            )
            customer_msg_html = render_to_string(
                'contact/email/customer_confirmation_mail.html',
                ctx
            )
            subject = _('Subject')
            message = customer_msg_plain
            from_email = settings.EMAIL_HOST_USER
            to_list = [request.user.email]
            send_mail(
                subject,
                message,
                from_email,
                to_list,
                html_message=customer_msg_html,
                fail_silently=True
            )
            ajaxData = {}
            ajaxData['success_msg'] = ('Success message')
            return HttpResponse(json.dumps(ajaxData))
        else:
            ajaxData = {}
            ajaxData['error_msg'] = ('Error message')
            return HttpResponse(json.dumps(ajaxData))
    else:
        form = forms.ContactForm()

    context = {
        'form': form,
    }
    return render(request, 'contact/contact_form.html', context)


def newsletter_form(request):
    current_site = get_current_site(request)
    if settings.MAILCHIMP_LIST_ID:
        list_id = settings.MAILCHIMP_LIST_ID
        instance = mailchimp.Mailchimp(settings.MAILCHIMP_API_KEY)
    else:
        list_id = current_site.siteextra.mailchimp_list_id
        instance = mailchimp.Mailchimp(current_site.siteextra.mailchimp_api_key)
    if request.method == 'POST':
        form = forms.NewsletterForm(request.POST or None)
        if form.is_valid():
            email = {"email": form.cleaned_data.get("email_address")}
            instance.lists.subscribe(
                list_id, email,
                double_optin=False,
                update_existing=True,
                send_welcome=False
            )
            ajaxData = {}
            ajaxData['success_msg'] = 'Success Newsletter message'
            return HttpResponse(json.dumps(ajaxData))
        else:
            ajaxData = {}
            ajaxData['error_msg'] = 'Error Newsletter message'
            return HttpResponse(json.dumps(ajaxData))
    else:
        form = forms.NewsletterForm()

    context = {
        'newsletter_form': form,
    }
    return render(request, 'contact/newsletter_form.html', context)

src/contact/templates/contact/contact_form.html
{% load crispy_forms_tags %}
{% load static %}

<div class="modal fade contact_modal contact_form_block" id="contactModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="d-flex justify-content-end">
				<button type="button" id="modal_close_c" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<h1 class="t_text90"></h1>
				<hr>
				<h2 class="t_text91"></h2>
				<form method="POST" id="contactForm" action="{% url 'contact:contactform' %}">{% csrf_token %}
					<div class="row">
						<div class="col-sm-6 col-xs-12">
							<div id="div_id_name" class="form-group">
								<div class="controls">
									<input class="textinput textInput form-control" id="id_name" maxlength="120" name="name" type="text" required />
									<p id="id_name_v" class="name_field"></p>
								</div>
							</div>
						</div>
						<div class="col-sm-6 col-xs-12">
							<div id="div_id_email" class="form-group">
								<div class="controls">
									<input class="textinput textInput form-control" id="id_email_c" maxlength="254" name="email" type="text" required />
									<p id="id_email_v" class="email_field"></p>
								</div>
							</div>
						</div>
						<div class="col-sm-12 col-xs-12">
							<div id="div_id_message" class="form-group">
								<div class="controls ">
									<textarea class="textarea form-control" cols="40" id="id_message" name="message" rows="10"></textarea>
									<p id="id_message_v" class="message_field"></p>
								</div>
							</div>
						</div>
						<div class="col-sm-12 col-xs-12 contact_submit_div">
							<button type="submit" value="" id="submit_btn" class="cap_button t_text324"></button>
						</div>
					</div>
					<div class="reply text-center"></div>
				</form>
			</div>
		</div>
	</div>
</div>

src/contact/templates/contact/newsletter_form.html
{% load crispy_forms_tags %}
{% load static %}

<div class="modal fade newsletter_modal newsletter_form_block" id="newsletterModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="d-flex justify-content-end">
				<button type="button" id="newsletter_modal_close" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<h1 class="t_text337"></h1>
				<hr>
				<h2 class="t_text338"></h2>
				<form method="POST" id="newsletter_form" action="{% url 'contact:newsletter' %}" class="mt-20">{% csrf_token %}
					<div class="container">
						<div class="row">
							<div id="div_id_email" class="col-12 align-self-center form-group">
								<div class="controls ">
									<input class="emailinput form-control" id="id_email_address" name="email_address" type="email" placeholder="Email" required />
									<p id="id_email_address_v" class="news_email_field"></p>
								</div>
							</div>
							<div class="col-12 align-self-center">
								<button type="submit" value="" id="subs_btn" class="t_text339 cap_button"></button>
								<div class="subs_reply text-center"></div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>