src/blog/urls.py
""" URLs for the blog app """

from django.conf.urls import url

from . import views

__author__ = 'Alamgir Kabir Roni, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.blog_list,
        name='blog_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.blog_detail,
        name='blog_detail'
    ),
]

src/eshop/urls.py
""" Urls for the eshop app """

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

__author__ = 'Sathi, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^panier/$',
        views.CartView.as_view(),
        name='cart'
    ),
    url(
        r'^notification/$',
        views.payment_notification,
        name='notification'
    ),
    url(
        r'^cart/count/$',
        views.ItemCountView.as_view(),
        name='item_count'
    ),
    url(
        r'^cart/item/remove$',
        views.RemoveCartItemAPIView.as_view(),
        name='cartitem_remove_api'
    ),
    url(
        r'^check-out/$',
        views.CheckoutView.as_view(),
        name='checkout'
    ),
    url(
        r'^check-out/adresse/$',
        views.AddressSelectFormView.as_view(),
        name='order_address'
    ),
    url(
        r'^check-out/adresse/ajouter/$',
        views.UserAddressCreateView.as_view(),
        name='user_address_create'
    ),
    url(
        r'^commandes/(?P<pk>\d+)/$',
        views.order_detail,
        name='order_detail'
    ),
    url(
        r'^commandes/paiement/$',
        views.Payment,
        name='payment'
    ),
    url(
        r'^check-out/final/$',
        views.CheckoutFinalView.as_view(),
        name='checkout_final'
    ),
    url(
        r'^orders/payment/after/',  # Linked to external payment module
        views.CheckoutFinalView.as_view(),
        name='payment_after'
    ),
    url(
        r'^order/confirmation/$',
        TemplateView.as_view(template_name='eshop/email/order_confirmation_mail.html')
    ),
    url(
        r'^order/invoice/$',
        TemplateView.as_view(template_name='eshop/invoice.html')
    ),

    # API
    url(
        r'^api/cart/$',
        views.CartAPIView.as_view(),
        name='cart_api'
    ),
]

src/mahdil/urls.py
""" mahdil URL Configuration """

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from mahdil.sitemaps import main_sitemaps

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = i18n_patterns(

    # Admin
    url(
        r'^admin/',
        include(admin.site.urls)
    ),

    # Third party apps URLs
    url(
        r'^accounts/',
        include('allauth.urls')
    ),
    url(
        r'^ckeditor/',
        include('ckeditor_uploader.urls')
    ),

    # Pages
    url(
        r'^',
        include('page.urls', namespace='page')
    ),
    url(
        r'^blog/',
        include('blog.urls', namespace='blog')
    ),
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),
    url(
        r'^eshop/',  # Linked to external payment module
        include('eshop.urls', namespace='eshop')
    ),
    url(
        r'^my-caps/',
        include('mycaps.urls', namespace='mycaps')
    ),
    url(
        r'^capsule-compatible-nespresso/',
        include('product.urls', namespace='product')
    ),
    url(
        r'^produits/',
        include('product.urls', namespace='product-others')
    ),
    url(
        r'^profil/',
        include('userprofile.urls', namespace='userprofile')
    ),
    url(
        r'^main/',
        include('main.urls', namespace='main')
    ),

    # API
    url(
        r'^api/main/',
        include('main.api.urls', namespace='main_api')
    ),
    url(
        r'^api/product/',
        include('product.api.urls', namespace='product_api')
    ),
    url(
        r'^api/page/',
        include('page.api.urls', namespace='page_api')
    ),

    # Sitemap,
    url(
        r'^sitemap\.xml$',
        sitemap, {'sitemaps': main_sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

urlpatterns += [

    # Robots,
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='main/robots.txt')
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/main/api/urls.py
""" API URLs for the main app """

from django.conf.urls import url

from . import views

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^seo/',
        views.SEOAPI.as_view(),
        name='api_seo'
    ),
    url(
        r'^text/$',
        views.TextAPI.as_view(),
        name='api_text'
    ),
    url(
        r'^text/(?P<pk>\d+)/',
        views.TextRetrieveAPI.as_view(),
        name='api_text_detail'
    ),
]

src/main/urls.py
""" URLs for the main app """

from django.conf.urls import url
from django.views.generic import TemplateView

__author__ = 'Sathi'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Errors pages
urlpatterns = [
    url(
        r'^error/400/$',
        TemplateView.as_view(template_name='main/error/400.html')
    ),
    url(
        r'^error/403/$',
        TemplateView.as_view(template_name='main/error/403.html')
    ),
    url(
        r'^error/403_csrf/$',
        TemplateView.as_view(template_name='main/error/403_csrf.html')
    ),
    url(
        r'^error/404/$',
        TemplateView.as_view(template_name='main/error/404.html')
    ),
    url(
        r'^error/500/$',
        TemplateView.as_view(template_name='main/error/500.html')
    ),
    url(
        r'^account/email_confirmation_message/$',
        TemplateView.as_view(template_name='account/email/email_confirmation_message.html')
    ),
    url(
        r'^account/email_confirmation_signup_message/$',
        TemplateView.as_view(template_name='account/email/email_confirmation_signup_message.html')
    ),
    url(
        r'^account/password_reset_key_message/$',
        TemplateView.as_view(template_name='account/email/password_reset_key_message.html')
    ),
]

src/page/urls.py
""" URLs for the page app """

from django.conf.urls import url

from . import views

__author__ = 'Sathi, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


urlpatterns = [
    url(
        r'^$',
        views.home,
        name='home'
    ),
    url(
        r'^cgv/$',
        views.cgv,
        name='cgv'
    ),
    url(
        r'^concept/$',
        views.concept,
        name='concept'
    ),
    url(
        r'^eshop/$',
        views.eshop,
        name='eshop'
    ),
    url(
        r'^faq/$',
        views.faq,
        name='faq'
    ),
    url(
        r'^legal_notice/$',
        views.legal_notice,
        name='legal_notice'
    ),
    url(
        r'^pro/$',
        views.pro,
        name='pro'
    ),
    url(
        r'^map/$',
        views.map,
        name='map'
    ),
    url(
        r'^boutiques/$',
        views.shop,
        name='shop'
    ),

    # To check
    url(
        r'^address/(?P<id>\d+)/edit/$',
        views.address_edit,
        name='address_edit'
    ),
    url(
        r'^api/shop/$',
        views.ShopAPIView.as_view(),
        name='shop_api'
    ),
]

src/product/urls.py
""" Urls for the product app """

from django.conf.urls import url

from . import views

__author__ = 'S. M. Sazedul Haque, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


urlpatterns = [
    url(
        r'^$',
        views.product_list,
        name='product_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.product_detail,
        name='product_detail'
    ),
    url(
        r'^categorie/(?P<slug>[\w-]+)/$',
        views.category_detail,
        name='category_detail'
    ),

    # API
    url(
        r'^api/product/list/$',
        views.ProductAPIView.as_view(),
        name='api_product_list'
    ),
]

src/main/api/views.py
""" API Views for the main app """

from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import AllowAny

from .. import models
from . import serializers

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# API Views
class SEOAPI(ListAPIView):
    permission_classes = [AllowAny]
    queryset = models.SEO.objects.all()
    serializer_class = serializers.SEOSerializer


class TextAPI(ListAPIView):
    permission_classes = [AllowAny]
    queryset = models.Text.objects.all()
    serializer_class = serializers.TextSerializer


class TextRetrieveAPI(RetrieveAPIView):
    permission_classes = [AllowAny]
    queryset = models.Text.objects.all()
    serializer_class = serializers.TextSerializer

src/main/templates/main/analytics.html
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', '{{ GOOGLE_ANALYTICS_ID }}', 'auto');
	ga('send', 'pageview');
</script>

src/main/templates/main/favicon.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'main/img/favicon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'main/img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'main/img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'main/img/favicon/manifest.json' %}">
<link rel="mask-icon" href="{% static 'main/img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
<meta name="theme-color" content="#ffffff">

src/main/templates/main/footer.html
{% load static %}

<div class="footer_block mm-bg t_bg182" style="background: url('');">
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="single-footer-widget">
					<a href="{% url 'page:home' %}"><h1 class="t_text68"></h1></a>
					<ul>
						<li><a href="{% url 'page:concept' %}" class="t_text69"></a></li>
						<li><a href="{% url 'product:product_list' %}" class="t_text71"></a></li>
						<li><a href="{% url 'blog:blog_list' %}" class="t_text70"></a></li>
						<!-- <li><a href="" class="t_text72"></a></li> -->
					</ul>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="single-footer-widget">
					<h1 class="text-uppercase t_text73"></h1>
					<ul>
						<li><a href="{% url 'page:shop' %}" class="t_text74"></a></li>
						<li><a href="{% url 'page:shop' %}" class="t_text75"></a></li>
						<li><a href="{% url 'page:faq' %}" class="">FAQ</a></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="single-footer-widget">
					<h1 class="text-uppercase t_text76"></h1>
					<p><a href="{% url 'page:pro' %}" class="t_text77"></a></p>
					<p class="t_text97"></p>
					{% if request.user.is_authenticated %}
					<form method="post" action="{% url 'account_logout' %}">
						{% csrf_token %}
						<button class="cap_button cap_button_v3 ml-0 t_text119" type="submit"></button>
					</form>
					{% else %}

					<a href="{% url 'account_login' %}" class="cap_button cap_button_v3 ml-0 t_text78"></a>
					{% endif %}
				</div>
			</div>
			<div class="col-sm-3">
				<div class="single-footer-widget">
					<h1 class="text-uppercase t_text79"></h1>
					<p class="t_text80"></p>
					<div class="social_links">
						<a href="" target="_blank" class="t_text34"><img src="" class="t_text179" /></a>
						<a href="" target="_blank" class="t_text36"><img src="" class="t_text180" /></a>
						<!-- <a href="" target="_blank" class="t_text35"><img src="" class="t_text181" /></a> -->
					</div>
				</div>
			</div>
		</div>
		<div class="copyright_div">
			<hr>
			<div class="row">
				<div class="col-sm-6 left_text">
					<ul>
						<li><a href="http://www.giordani.paris/" target="_blank">Artwork : Giordani</a></li>
						<li>Développement : <a href="https://mahdil.com/" target="_blank">Maison Mahdil {% now 'Y' %}</a></li>
					</ul>
				</div>
				<div class="col-sm-6 right_text">
					<ul>
						<li><a href="{% url 'page:legal_notice' %}" class="t_text81"></a></li>
						<li><a href="{% url 'page:cgv' %}" class="t_text82"></a></li>
						<!-- <li class="t_text84"></li> -->
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

src/main/templates/main/head_css.html
{% load static %}

{% if not live_test %}

<!-- Vendor css file -->
<link rel="stylesheet" href="{% static 'bower_components/font-awesome/web-fonts-with-css/css/fontawesome.min.css' %}">
<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'bower_components/slick-carousel/slick/slick.css' %}">

<!-- Mahdil css file -->
{% if current_site.id == 2 %}
<link rel="stylesheet" href="{% static 'main/css/conservatoire.css' %}{{ v }}">
{% else %}
<link rel="stylesheet" href="{% static 'main/css/capsulier.css' %}{{ v }}">
{% endif %}

{% else %}

<!-- Vendor css file -->
<link rel="stylesheet" href="{% static 'vendor/font-awesome/web-fonts-with-css/css/fontawesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/slick-carousel/slick/slick.css' %}">

<!-- Mahdil css file -->
{% if current_site.id == 2 %}
<link rel="stylesheet" href="{% static 'main/dist/conservatoire.min.css' %}{{ v }}">
{% else %}
<link rel="stylesheet" href="{% static 'main/dist/capsulier.min.css' %}{{ v }}">
{% endif %}

{% endif %}

src/main/templates/main/head_js.html
{% load static %}

{% if not live_test %}
<script src="http://localhost:35729/livereload.js"></script>

<!-- Vendor js file -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bower_components/infinite-scroll/dist/infinite-scroll.pkgd.min.js' %}"></script>
<script src="{% static 'bower_components/bootbox.js/bootbox.js' %}"></script>
<script src="{% static 'bower_components/slick-carousel/slick/slick.js' %}"></script>

<!-- Mahdil js file -->
<script src="{% static 'contact/js/contact_form.js' %}{{ v }}"></script>
<script src="{% static 'contact/js/newsletter_form.js' %}{{ v }}"></script>
<script src="{% static 'main/js/main.js' %}{{ v }}"></script>

{% else %}

<!-- Vendor js file -->
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/infinite-scroll/dist/infinite-scroll.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/bootbox.js/bootbox.js' %}"></script>
<script src="{% static 'vendor/slick-carousel/slick/slick.min.js' %}"></script>

<!-- Mahdil js file -->
<script src="{% static 'contact/dist/contact_form.min.js' %}{{ v }}"></script>
<script src="{% static 'contact/dist/newsletter_form.min.js' %}{{ v }}"></script>
<script src="{% static 'main/dist/main.min.js' %}{{ v }}"></script>

{% endif %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'assets/js/vendor/ie10-viewport-bug-workaround.js' %}"></script>

<script>

	function updateCartItemCount(){
		var badge = $("#cart-count-badge");

		$.ajax({
			type: "GET",
			url: "{% url 'eshop:item_count' %}",
			success: function(data){
				badge.text(data.count);

			},
			error: function(response, error) {
				console.log(response);
				console.log(error);
			}

		});

	}
	$(document).ready(function(){

		updateCartItemCount();
	});

</script>

<script>

	function updateCartItemCount(){
		var badge2 = $("#cart-count-badge");

		$.ajax({
			type: "GET",
			url: "{% url 'eshop:item_count' %}",
			success: function(data){
				badge2.text(data.count);
				// console.log(data.count);
			},
			error: function(response, error) {
				console.log(response);
				console.log(error);
			}

		});

	}
	$(document).ready(function(){

		updateCartItemCount();
	});

</script>

src/main/templates/main/loader.html
<div id="mm-loader-wrapper">
    <div id="mm-loader"></div>
</div>

src/main/templates/main/meta.html
{% load cropping %}
{% load static %}

<title>{% block head_title %}{% endblock %}{{ seo_main.title }}</title>
<meta name="author" content="Maison Mahdil" />
<meta name="description" content="{% block seo_description %}{{ seo_main.description }}{% endblock %}"/>
<meta name="Resource-type" content="{% block seo_resource_type %}{{ seo_main.resource_type }}{% endblock %}" />
<!-- To change when live iwht static and media link -->
<link rel="image_src" href="{{ request.build_absolute_uri|slice:':-1' }}{% block seo_image %}{% if seo_main.image %}{{ seo_main 'image_cropping' scale=1 %}{% endif %}{% endblock %}"/>

<!-- Facebook -->
<meta property="fb:app_id" content="{{ seo_main.fb_app_id }}" />
<meta property="og:description" content="{% block seo_description_f %}{{ seo_main.description }}{% endblock %}"/>
<!-- To change when live with static and media link -->
<meta property="og:image" content="{{ request.build_absolute_uri|slice:':-1' }}{% block seo_image_f %}{% if seo_main.image %}{{ seo_main 'image_cropping' scale=1 %}{% endif %}{% endblock %}"/>
<meta property="og:title" content="{% block head_title_f %}{% endblock %}{{ seo_main.title }}"/>
<meta property="og:url" content="{{ request.build_absolute_uri }}"/>
<meta property="og:site_name" content="{{ seo_main.site_name }}"/>
<meta property="og:locale" content="{{ request.LANGUAGE_CODE }}_FR"/>
<meta name="my:fb" content="on"/>
<meta name="my:google" content="on"/>
<meta name="my:tw" content="on"/>
<meta name="my:in" content="on"/>


<!-- Twitter -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="{{ seo_main.twitter_site }}" />
<meta name="twitter:title" content="{% block head_title_t %}{% endblock %}{{ seo_main.title }}" />
<meta name="twitter:description" content="{% block seo_description_t %}{{ seo_main.description }}{% endblock %}" />
<!-- To change when live with static and media link -->
<meta name="twitter:image" content="{{ request.build_absolute_uri|slice:':-1' }}{% block seo_image_t %}{% if seo_main.image %}{{ seo_main 'image_cropping' scale=1 %}{% endif %}{% endblock %}" />

<!-- Google -->
<script type="application/ld+json">
	{
		"@context": "http://schema.org/",
		"@type": "WebSite",
		"name": "{% block head_title_g %}{% endblock %}{{ seo_main.title }}",
		/*To change when live with static and media link*/
		"image": "{{ request.build_absolute_uri|slice:':-1' }}{% block seo_image_g %}{% if seo_main.image %}{{ seo_main 'image_cropping' scale=1 %}{% endif %}{% endblock %}",
		"description": "{% block seo_description_g %}{{ seo_main.description }}{% endblock %}"
	}
</script>

<meta name="google-site-verification" content="2ycvowazjavwNx_3RC8pXtbz-LGlU0HUZ4ZrvlK1jdI" />

src/main/templates/main/meta_block.html
{% block head_title %}{% endblock %}
{% block head_title_f %}{% endblock %}
{% block head_title_g %}{% endblock %}
{% block head_title_t %}{% endblock %}

{% block seo_description %}{% endblock %}
{% block seo_description_f %}{% endblock %}
{% block seo_description_g %}{% endblock %}
{% block seo_description_t %}{% endblock %}

{% block seo_image %}{% endblock %}
{% block seo_image_f %}{% endblock %}
{% block seo_image_g %}{% endblock %}
{% block seo_image_t %}{% endblock %}

{% block seo_resource_type %}{% endblock %}