src/blog/urls.py
""" URLs for the blog app """

from django.conf.urls import url

from . import views

__author__ = 'Alamgir Kabir Roni, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.blog_list,
        name='blog_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.blog_detail,
        name='blog_detail'
    ),
]

src/mahdil/urls.py
""" mahdil URL Configuration """

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from mahdil.sitemaps import main_sitemaps

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = i18n_patterns(

    # Admin
    url(
        r'^admin/',
        include(admin.site.urls)
    ),

    # Third party apps URLs
    url(
        r'^accounts/',
        include('allauth.urls')
    ),
    url(
        r'^ckeditor/',
        include('ckeditor_uploader.urls')
    ),

    # Pages
    url(
        r'^',
        include('page.urls', namespace='page')
    ),
    url(
        r'^blog/',
        include('blog.urls', namespace='blog')
    ),
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),
    url(
        r'^eshop/',  # Linked to external payment module
        include('eshop.urls', namespace='eshop')
    ),
    url(
        r'^my-caps/',
        include('mycaps.urls', namespace='mycaps')
    ),
    url(
        r'^capsule-compatible-nespresso/',
        include('product.urls', namespace='product')
    ),
    url(
        r'^produits/',
        include('product.urls', namespace='product-others')
    ),
    url(
        r'^profil/',
        include('userprofile.urls', namespace='userprofile')
    ),
    url(
        r'^main/',
        include('main.urls', namespace='main')
    ),

    # API
    url(
        r'^api/main/',
        include('main.api.urls', namespace='main_api')
    ),
    url(
        r'^api/product/',
        include('product.api.urls', namespace='product_api')
    ),
    url(
        r'^api/page/',
        include('page.api.urls', namespace='page_api')
    ),

    # Sitemap,
    url(
        r'^sitemap\.xml$',
        sitemap, {'sitemaps': main_sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

urlpatterns += [

    # Robots,
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='main/robots.txt')
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/mycaps/urls.py
""" URLs for the mycaps app """

from django.conf.urls import url

from . import views

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.mycaps,
        name='mycaps',
    ),
    url(
        r'^crop/$',
        views.crop,
        name='crop'
    ),
]

src/mycaps/models.py
""" Models for the mycaps app """

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from easy_thumbnails.exceptions import InvalidImageFormatError
from easy_thumbnails.files import get_thumbnailer

from product.models import Product

from . import utils

__author__ = 'Aupourbau Koumar, Alamgir Kabir Roni'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Models
class Coffee(models.Model):

    # Attributes
    title = models.CharField(
        _('title'),
        max_length=200,
        unique=True,
    )
    description = models.TextField(
        _('description'),
        blank=True,
    )
    image = models.FileField(
        _('image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )

    # Metadata
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        blank=True,
        editable=False,
        null=True,
    )
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='+',
        verbose_name=_('created by'),
    )
    updated_on = models.DateTimeField(
        _('updated on'),
        auto_now=True,
        editable=False,
        null=True,
    )
    updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='+',
        verbose_name=_('updated by'),
    )

    # Functions
    def __unicode__(self):
        return self.title

    def __unicode__(self):
        return u"%s" % (self.title)

    def get_image_box(self):
        if self.image:
            try:
                img = self.image.url
                return mark_safe('<img src="%s" width="120px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box.short_description = _('Coffee Image')


class Color(models.Model):

    # Attributes
    name = models.CharField(
        _('name'),
        max_length=200,
        unique=True,
    )
    color = models.CharField(
        _('color'),
        max_length=200,
    )
    image = models.ImageField(
        _('image'),
        blank=False,
        upload_to=utils.mycaps_upload_to,
    )
    color_image = models.ImageField(
        _('color image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )
    package_image = models.ImageField(
        _('package image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )
    background_image = models.ImageField(
        _('background image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )

    # Metadata
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        blank=True,
        editable=False,
        null=True,
    )
    created_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='+',
        verbose_name=_('created by'),
    )
    updated_on = models.DateTimeField(
        _('updated on'),
        auto_now=True,
        editable=False,
        null=True,
    )
    updated_by = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='+',
        verbose_name=_('updated by'),
    )

    # Functions
    def __unicode__(self):
        return self.name

    def __unicode__(self):
        return u"%s" % (self.name)

    def get_image_box(self):
        if self.image:
            try:
                img = get_thumbnailer(self.image).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="80px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box.short_description = _('Image')

    def get_image_box_color(self):
        if self.color_image:
            try:
                img = get_thumbnailer(self.color_image).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="120px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box_color.short_description = _('Color Image')

    def get_image_box_package(self):
        if self.package_image:
            try:
                img = get_thumbnailer(self.package_image).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="120px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box_package.short_description = _('Package Image')

    def get_image_box_background(self):
        if self.background_image:
            try:
                img = get_thumbnailer(self.background_image).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="120px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box_background.short_description = _('Background Image')


class Package(models.Model):

    # Relations
    coffee = models.ForeignKey(
        Coffee,
        verbose_name=_('coffee'),
        related_name='packagebycoffee',
    )
    color = models.ForeignKey(
        Color,
        verbose_name=_('color'),
        related_name='packagebycolor',
    )
    product = models.ForeignKey(
        Product,
        verbose_name=_('product'),
        related_name='packagebyproduct',
        default='310',
    )

    # Attributes
    image = models.ImageField(
        _('image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )
    image1 = models.ImageField(
        _('image1'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )
    text1 = models.CharField(
        _('text for capsule'),
        max_length=200,
        blank=True,
    )
    text2 = models.CharField(
        _('text for package'),
        max_length=200,
        blank=True,
    )
    active = models.BooleanField(
        _('active'),
        default=True,
    )

    # Metadata
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        editable=False,
    )
    updated_on = models.DateTimeField(
        _('updated on'),
        auto_now=True,
        editable=False,
        null=True,
    )

    # Functions
    def __unicode__(self):
        return self.id

    def __unicode__(self):
        return u"%s" % (self.id)

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def get_image_box(self):
        if self.image:
            try:
                img = get_thumbnailer(self.image).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="200px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box.short_description = _('Image')

    def get_image_box2(self):
        if self.image1:
            try:
                img = get_thumbnailer(self.image1).get_thumbnail({
                    'size': (400, 0),
                    'detail': True,
                }).url
                return mark_safe('<img src="%s" width="200px" />' % img)
            except InvalidImageFormatError:
                return "%s" % (_('Image File Error'))
        else:
            return "%s" % (_('None'))
    get_image_box.short_description = _('Image2')

    def add_to_cart(self):
        return "%s?package=%s&qty=1" % (reverse('eshop:cart'), self.id)

    def remove_from_cart(self):
        return "%s?package=%s&qty=1&delete=True" % (reverse('eshop:cart'), self.id)

    def get_title(self):
        return "%s - %s" % (self.product.name, self.title)
    # Meta

    class Meta:
        ordering = ['id']
        verbose_name = _('package')
        verbose_name_plural = _('packages')


class Crop(models.Model):
    image = models.ImageField(
        _('image'),
        blank=True,
        upload_to=utils.mycaps_upload_to,
    )

    # Metadata
    created_on = models.DateTimeField(
        _('created on'),
        auto_now_add=True,
        editable=False,
    )
    updated_on = models.DateTimeField(
        _('updated on'),
        auto_now=True,
        editable=False,
        null=True,
    )

    class Meta:
        ordering = ['id']
        verbose_name = _('crop')
        verbose_name_plural = _('cropes')

src/mycaps/forms.py
""" Forms for the mycaps app """

from PIL import Image
from django import forms

from . import models

__author__ = 'Aupourbau Koumar, Alamgir Kabir Roni'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Forms
class PackageForm(forms.ModelForm):
    x = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    y = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    width = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    height = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    x1 = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    y1 = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    width1 = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )
    height1 = forms.FloatField(
        widget=forms.HiddenInput(
            attrs={'required': 'false'}
        )
    )

    class Meta:
        model = models.Package

        fields = [
            'color',
            'coffee',
            'text1',
            'text2',
            'image',
            'x',
            'y',
            'width',
            'height',
            'image1',
            'x1',
            'y1',
            'width1',
            'height1',
        ]

    def save(self):
        photo = super(PackageForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        image = Image.open(photo.image)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
        resized_image.save(photo.image.path)

        return photo

        photo1 = super(PackageForm, self).save()
        x1 = self.cleaned_data.get('x1')
        y1 = self.cleaned_data.get('y1')
        w1 = self.cleaned_data.get('width1')
        h1 = self.cleaned_data.get('height1')

        # if self.cleaned_data.get('image'):
        image1 = Image.open(photo1.image1)
        cropped_image1 = image1.crop((x1, y1, w1 + x1, h1 + y1))
        resized_image1 = cropped_image1.resize((400, 400), Image.ANTIALIAS)
        resized_image1.save(photo1.image1.path)

        return photo1


# class PackageForm2(forms.ModelForm):
#     x = forms.FloatField(widget=forms.HiddenInput())
#     y = forms.FloatField(widget=forms.HiddenInput())
#     width = forms.FloatField(widget=forms.HiddenInput())
#     height = forms.FloatField(widget=forms.HiddenInput())

#     class Meta:
#         model = Crop

#         fields = [
#             'image',
#             'x',
#             'y',
#             'width',
#             'height',
#         ]
#         widgets = {
#             'image': forms.FileInput(attrs={
#                 'accept': 'image/*',
#                 'required': 'false',
#             })
#         }

#     def save(self):
#         print 'in my caps form'
#         print self
#         photo = super(PackageForm2, self).save()
#         print 'in my caps form photo section'
#         print photo

#         x = self.cleaned_data.get('x')
#         y = self.cleaned_data.get('y')
#         w = self.cleaned_data.get('width')
#         h = self.cleaned_data.get('height')

#         image = Image.open(photo.image)
#         cropped_image = image.crop((x, y, w+x, h+y))
#         resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
#         resized_image.save(photo.image.path)

#         return photo

src/mycaps/templates/package/crop-old.html
{% load static %}

{% block head_title %} | {% endblock %}
{% block seo_description %}{% endblock %}

{% block head_css %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'mycaps/css/mycaps.css' %}">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mycaps/css/cropper.min.css' %}">
<script src="{% static 'mycaps/js/cropper.min.js' %}"></script>

<h1 class="page-header">Album</h1>
<!-- FORM TO UPLOAD THE IMAGES -->
<form class="col-md-10" method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
    <img src="http://via.placeholder.com/800x400" id="image2" class="img-responsive">
</form>
<button type="button" class="btn btn-default js-zoom-in">
  <span class="glyphicon glyphicon-zoom-in"></span>
</button>
<button type="button" class="btn btn-default js-zoom-out">
  <span class="glyphicon glyphicon-zoom-out"></span>
</button>
<button class="js-crop-and-upload btn-lg">submit</button>
<div class="container">
  <div class="row">
      {% for p in photo %}
      <div class="col-md-3">
          <img src="{{ p.image.url }}" class="thumbnail img-responsive">
      </div>
      {% endfor %}
  </div>
</div>

<script type="text/javascript">
 // crop function start here
 $(function () {
  var $image = $("#image2");
  $("#id_image").change(function () {
     $image.cropper("destroy");
     if (this.files && this.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e){
        $("#image2").attr("src", e.target.result);
        $("#image").attr("src", e.target.result);

        var cropBoxData;
        var canvasData;
        $image.cropper({
           viewMode: 4,
           aspectRatio: 6/2,
           minCropBoxWidth: 400,
           minCropBoxHeight: 800,
           rotate: 45,
           ready: function () {
             $image.cropper("setCanvasData", canvasData);
             $image.cropper("setCropBoxData", cropBoxData);
         }
     });
    };
    reader.readAsDataURL(this.files[0]);
}
});

  $(".js-zoom-in").click(function () {
    $image.cropper("zoom", 0.1);
});

  $(".js-zoom-out").click(function () {
    $image.cropper("zoom", -0.1);
});

  // submit form with crop data
  $(".js-crop-and-upload").click(function () {
    var cropData = $image.cropper("getData");
    console.log(cropData);
    $("#id_x").val(cropData["x"]);
    $("#id_y").val(cropData["y"]);
    $("#id_height").val(cropData["height"]);
    $("#id_width").val(cropData["width"]);
    $("#formUpload").submit();
});

});

</script>





{% endblock %}

src/mycaps/templates/package/crop-round.html
{% load static %}

{% block head_title %} | {% endblock %}
{% block seo_description %}{% endblock %}

{% block head_css %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'mycaps/css/mycaps.css' %}">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mycaps/css/cropper.min.css' %}">
<script src="{% static 'mycaps/js/cropper.min.js' %}"></script>

<style>
    .container {
      margin: 20px auto;
      max-width: 640px;
    }
    img {
        max-width: 100%;
    }
    .cropper-view-box, .cropper-face {
        border-radius: 50%;
    }
</style>

<div class="container">
    <h1>Crop a round image</h1>
    <h3>Image</h3>
    <div>
      <img id="image" src="{% static 'mycaps/img/caps-red.png' %}" alt="Picture">
  </div>
  <h3>Result</h3>
  <button type="button" id="button">Crop</button>
  <div id="result"></div>
</div>

<script>
    function getRoundedCanvas(sourceCanvas) {
      var canvas = document.createElement('canvas');
      var context = canvas.getContext('2d');
      var width = sourceCanvas.width;
      var height = sourceCanvas.height;
      canvas.width = width;
      canvas.height = height;
      context.beginPath();
      context.arc(width / 2, height / 2, Math.min(width, height) / 2, 0, 2 * Math.PI);
      context.strokeStyle = 'rgba(0,0,0,0)';
      context.stroke();
      context.clip();
      context.drawImage(sourceCanvas, 0, 0, width, height);
      return canvas;
  }
  $(function () {
      var $image = $('#image');
      var $button = $('#button');
      var $result = $('#result');
      var croppable = false;
      $image.cropper({
        aspectRatio: 1,
        viewMode: 1,
        ready: function () {
          croppable = true;
      }
  });
      $button.on('click', function () {
        var croppedCanvas;
        var roundedCanvas;
        if (!croppable) {
          return;
      }
        // Crop
        croppedCanvas = $image.cropper('getCroppedCanvas');
        // Round
        roundedCanvas = getRoundedCanvas(croppedCanvas);
        // Show
        $result.html('<img src="' + roundedCanvas.toDataURL() + '">');
    });
  });
</script>

{% endblock %}

src/mycaps/templates/package/crop.html
{% load static %}

{% block head_title %} | {% endblock %}
{% block seo_description %}{% endblock %}

{% block head_css %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'mycaps/css/mycaps.css' %}">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mycaps/css/cropper.min.css' %}">
<script src="{% static 'mycaps/js/cropper.min.js' %}"></script>

<style>
  .container {
    margin: 20px auto;
    max-width: 640px;
}
img {
    max-width: 100%;
}
.cropper-view-box, .cropper-face {
    border-radius: 50%;
}
</style>


<div class="container">
  <h1>Crop a round image</h1>
  <h3>Image</h3>
  <div>
      <form class="col-md-10" method="post" enctype="multipart/form-data" id="formUpload">
          {% csrf_token %}
          {{ form }}
      </form>
      <img id="image2" src="{% static 'mycaps/img/bitmap.jpg' %}" alt="Picture">
  </div>
  <h3>Result</h3>
  <button type="button" id="button">Crop</button>
  <div id="result"></div>
</div>

<div class="container">
  <div class="row">
      {% for p in photo %}
      <div class="col-md-3">
          <img src="{{ p.image.url }}" class="thumbnail img-responsive">
      </div>
      {% endfor %}
  </div>
</div>


<script>
    function getRoundedCanvas(sourceCanvas) {
      var canvas = document.createElement('canvas');
      var context = canvas.getContext('2d');
      var width = sourceCanvas.width;
      var height = sourceCanvas.height;
      canvas.width = width;
      canvas.height = height;
      context.beginPath();
      context.arc(width / 2, height / 2, Math.min(width, height) / 2, 0, 2 * Math.PI);
      context.strokeStyle = 'rgba(0,0,0,0)';
      context.stroke();
      context.clip();
      context.drawImage(sourceCanvas, 0, 0, width, height);
      console.log(canvas);
      return canvas;
  }
    // $(function () {
      var $image = $('#image2');
      var $button = $('#button');
      var $result = $('#result');
      // var croppable = false;

      // if (this.files && this.files[0]) {
      //   var reader = new FileReader();
      //     reader.onload = function (e){
      //       $("#image2").attr("src", e.target.result);
      //       $image.cropper({
      //         aspectRatio: 1,
      //         viewMode: 1,
      //         ready: function () {
      //           croppable = true;
      //         }
      //       });
      //     };
      //     reader.readAsDataURL(this.files[0]);
      //   }
      // });
      var $image = $("#image2");
      $("#id_image").change(function () {
         $image.cropper("destroy");
         if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e){
            $("#image2").attr("src", e.target.result);
            $("#image").attr("src", e.target.result);
            console.log(e);
          // var cropBoxData;
          // var canvasData;
          $image.cropper({
           aspectRatio: 1,
           viewMode: 1,
           ready: function () {
            croppable = true;
        }
    });
      };
      reader.readAsDataURL(this.files[0]);
  }
});

      $button.on('click', function () {

        var cropData = $image.cropper("getData");
        console.log(cropData);

        var croppedCanvas;
        var roundedCanvas;
        if (!croppable) {
          return;
      }
        // Crop
        croppedCanvas = $image.cropper('getCroppedCanvas');
        // Round
        roundedCanvas = getRoundedCanvas(croppedCanvas);
        // Show
        $result.html('<img src="' + roundedCanvas.toDataURL() + '">');

        // $("#id_image").val(roundedCanvas.toDataURL());
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        // $("#formUpload").submit();
    });
    // });

</script>

{% endblock %}