src/blog/urls.py
""" URLs for the blog app """

from django.conf.urls import url

from . import views

__author__ = 'Alamgir Kabir Roni, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.blog_list,
        name='blog_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.blog_detail,
        name='blog_detail'
    ),
]

src/eshop/urls.py
""" Urls for the eshop app """

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

__author__ = 'Sathi, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^panier/$',
        views.CartView.as_view(),
        name='cart'
    ),
    url(
        r'^notification/$',
        views.payment_notification,
        name='notification'
    ),
    url(
        r'^cart/count/$',
        views.ItemCountView.as_view(),
        name='item_count'
    ),
    url(
        r'^cart/item/remove$',
        views.RemoveCartItemAPIView.as_view(),
        name='cartitem_remove_api'
    ),
    url(
        r'^check-out/$',
        views.CheckoutView.as_view(),
        name='checkout'
    ),
    url(
        r'^check-out/adresse/$',
        views.AddressSelectFormView.as_view(),
        name='order_address'
    ),
    url(
        r'^check-out/adresse/ajouter/$',
        views.UserAddressCreateView.as_view(),
        name='user_address_create'
    ),
    url(
        r'^commandes/(?P<pk>\d+)/$',
        views.order_detail,
        name='order_detail'
    ),
    url(
        r'^commandes/paiement/$',
        views.Payment,
        name='payment'
    ),
    url(
        r'^check-out/final/$',
        views.CheckoutFinalView.as_view(),
        name='checkout_final'
    ),
    url(
        r'^orders/payment/after/',  # Linked to external payment module
        views.CheckoutFinalView.as_view(),
        name='payment_after'
    ),
    url(
        r'^order/confirmation/$',
        TemplateView.as_view(template_name='eshop/email/order_confirmation_mail.html')
    ),
    url(
        r'^order/invoice/$',
        TemplateView.as_view(template_name='eshop/invoice.html')
    ),

    # API
    url(
        r'^api/cart/$',
        views.CartAPIView.as_view(),
        name='cart_api'
    ),
]

src/mahdil/urls.py
""" mahdil URL Configuration """

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from mahdil.sitemaps import main_sitemaps

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = i18n_patterns(

    # Admin
    url(
        r'^admin/',
        include(admin.site.urls)
    ),

    # Third party apps URLs
    url(
        r'^accounts/',
        include('allauth.urls')
    ),
    url(
        r'^ckeditor/',
        include('ckeditor_uploader.urls')
    ),

    # Pages
    url(
        r'^',
        include('page.urls', namespace='page')
    ),
    url(
        r'^blog/',
        include('blog.urls', namespace='blog')
    ),
    url(
        r'^contact/',
        include('contact.urls', namespace='contact')
    ),
    url(
        r'^eshop/',  # Linked to external payment module
        include('eshop.urls', namespace='eshop')
    ),
    url(
        r'^my-caps/',
        include('mycaps.urls', namespace='mycaps')
    ),
    url(
        r'^capsule-compatible-nespresso/',
        include('product.urls', namespace='product')
    ),
    url(
        r'^produits/',
        include('product.urls', namespace='product-others')
    ),
    url(
        r'^profil/',
        include('userprofile.urls', namespace='userprofile')
    ),
    url(
        r'^main/',
        include('main.urls', namespace='main')
    ),

    # API
    url(
        r'^api/main/',
        include('main.api.urls', namespace='main_api')
    ),
    url(
        r'^api/product/',
        include('product.api.urls', namespace='product_api')
    ),
    url(
        r'^api/page/',
        include('page.api.urls', namespace='page_api')
    ),

    # Sitemap,
    url(
        r'^sitemap\.xml$',
        sitemap, {'sitemaps': main_sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)

urlpatterns += [

    # Robots,
    url(
        r'^robots\.txt$',
        TemplateView.as_view(template_name='main/robots.txt')
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/mycaps/urls.py
""" URLs for the mycaps app """

from django.conf.urls import url

from . import views

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^$',
        views.mycaps,
        name='mycaps',
    ),
    url(
        r'^crop/$',
        views.crop,
        name='crop'
    ),
]

src/page/api/urls.py
""" API URLs for the main app """

from django.conf.urls import url

from . import views

__author__ = 'Alamgir Kabir Roni'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# URLs
urlpatterns = [
    url(
        r'^concept/map/$',
        views.ConceptMapAPIView.as_view(),
        name='concept_map'
    ),
]

src/page/urls.py
""" URLs for the page app """

from django.conf.urls import url

from . import views

__author__ = 'Sathi, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


urlpatterns = [
    url(
        r'^$',
        views.home,
        name='home'
    ),
    url(
        r'^cgv/$',
        views.cgv,
        name='cgv'
    ),
    url(
        r'^concept/$',
        views.concept,
        name='concept'
    ),
    url(
        r'^eshop/$',
        views.eshop,
        name='eshop'
    ),
    url(
        r'^faq/$',
        views.faq,
        name='faq'
    ),
    url(
        r'^legal_notice/$',
        views.legal_notice,
        name='legal_notice'
    ),
    url(
        r'^pro/$',
        views.pro,
        name='pro'
    ),
    url(
        r'^map/$',
        views.map,
        name='map'
    ),
    url(
        r'^boutiques/$',
        views.shop,
        name='shop'
    ),

    # To check
    url(
        r'^address/(?P<id>\d+)/edit/$',
        views.address_edit,
        name='address_edit'
    ),
    url(
        r'^api/shop/$',
        views.ShopAPIView.as_view(),
        name='shop_api'
    ),
]

src/product/urls.py
""" Urls for the product app """

from django.conf.urls import url

from . import views

__author__ = 'S. M. Sazedul Haque, Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


urlpatterns = [
    url(
        r'^$',
        views.product_list,
        name='product_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.product_detail,
        name='product_detail'
    ),
    url(
        r'^categorie/(?P<slug>[\w-]+)/$',
        views.category_detail,
        name='category_detail'
    ),

    # API
    url(
        r'^api/product/list/$',
        views.ProductAPIView.as_view(),
        name='api_product_list'
    ),
]

src/eshop/views.py
# -*- coding: utf-8 -*-
# pylint: disable=E501

""" Views for the cart app """

from datetime import datetime
from decimal import Decimal
from hashlib import sha1
from itertools import chain

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin, DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from allauth.account.forms import LoginForm
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from product.models import Variation, Product

from . import forms
from . import mixins
from . import models
from . import serializers

__author__ = 'Aupourbau Koumar'
__copyright__ = 'Copyright 2018, Maison Mahdil'


# Views
@login_required
def address_edit(request, id):
    address_instance = models.UserAddress.objects.get(id=id)
    if request.method == 'POST':
        form = forms.UserAddressForm(
            request.POST or None,
            request.FILES or None,
            instance=address_instance
        )
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user.usercheckout
            instance.save()
            return HttpResponseRedirect(reverse('userprofile:profile'))
    else:
        form = forms.UserAddressForm(instance=address_instance)
    context = {
        'form': form,
        'instance': address_instance,
    }
    return render(request, 'eshop/address_edit.html', context)


@login_required
def order_detail(request, pk):
    order_instance = models.Order.objects.get(pk=pk)
    if request.user.is_staff or request.user == order_instance.user_checkout.user:
        context = {
            'instance': order_instance,
        }
        return render(request, 'eshop/order_detail.html', context)
    raise Http404


# To clean
class ItemCountView(View):

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            cart_id = self.request.session.get('cart_id')
            if cart_id is None:
                count = 0
            else:
                cart = models.Cart.objects.get(id=cart_id)
                cart_item_list = cart.cartitem_set.all()
                count = 0
                for obj in cart_item_list:
                    count += obj.quantity
            request.session['cart_item_count'] = count
            return JsonResponse({'count': count})
        else:
            raise Http404


class CartView(SingleObjectMixin, View):
    model = models.Cart

    def get_object(self, *args, **kwargs):
        self.request.session.set_expiry(0)
        cart_id = self.request.session.get('cart_id')
        if cart_id is None:
            cart = models.Cart()
            cart.save()
            cart_id = cart.id
            self.request.session['cart_id'] = cart_id
        cart = models.Cart.objects.get(id=cart_id)
        if self.request.user.is_authenticated():
            cart.user = self.request.user
            cart.save()
        return cart

    def get_price(self, instance):
        if self.request.user.is_authenticated and self.request.user.profile.status == 'b':
            return instance.price_pro
        return instance.price_public

    def cart_item_price(self, itemInstance, quantity):
        if quantity >= 1:
            price = self.get_price(itemInstance.item)
            itemInstance.unit_price = Decimal(price)
            itemInstance.save()
        itemInstance.cart.save()

    def get(self, request, *args, **kwargs):
        cart = self.get_object()
        item_id = request.GET.get('item')
        delete_item = request.GET.get('delete', False)
        remove_qty = request.GET.get('remove')
        coupon_code = request.GET.get('coupon')
        shipping_service = request.GET.get('shipping')

        # Add item
        if item_id and not remove_qty:
            item_instance = get_object_or_404(Variation, id=item_id)
            qty = request.GET.get('qty', 1)
            try:
                if int(qty) < 1:
                    delete_item = True
            except:
                raise Http404

            cart_item, created = models.CartItem.objects.get_or_create(
                cart=cart,
                item=item_instance
            )
            self.cart_item_price(cart_item, qty)
            if delete_item:
                cart_item.delete()
            else:
                if created:
                    cart_item.quantity = float(qty)
                else:
                    cart_item.quantity = float(qty) + float(cart_item.quantity)
                cart_item.save()
            if not request.is_ajax():
                return HttpResponseRedirect(reverse('eshop:cart'))

        # Remove Qty
        if remove_qty:
            item_instance = get_object_or_404(Variation, id=item_id)
            cart_item = models.CartItem.objects.get(
                cart=cart,
                item=item_instance
            )
            if cart_item.quantity == 1:
                pass
            else:
                cart_item.quantity = float(cart_item.quantity) - float(1)
                cart_item.save()
            if not request.is_ajax():
                return HttpResponseRedirect(reverse('eshop:cart'))

        # Coupon
        if coupon_code:
            try:
                coupon_object = models.PromoCode.objects.get(code=coupon_code)
                cart.promo_code = coupon_object
                cart.save()
            except:
                cart.promo_code = None
                cart.save()

        # Shipping
        if shipping_service:
            print 'shipping'
            try:
                shipping_object = models.ShippingService.objects.get(id=shipping_service)
                print shipping_object
                cart.shipping_service = shipping_object
                cart.save()
            except:
                print 'none'
                cart.shipping_service = None
                cart.save()

        # Return json data
        if item_id:
            cart_item = models.CartItem.objects.filter(cart_id=cart.id)
            cart_item2 = cart_item.get(item_id=item_id)
            if request.is_ajax():
                try:
                    line_total = cart_item2.line_item_total
                except:
                    line_total = None
                try:
                    price = cart_item2.item.price
                except:
                    price = None
                try:
                    subtotal = cart_item2.cart.subtotal
                except:
                    subtotal = None
                try:
                    promo_code = cart.promo_code.code
                except:
                    promo_code = None
                try:
                    discount_total = cart.discount_total
                except:
                    discount_total = None
                try:
                    shipping_total = cart.shipping_total
                except:
                    shipping_total = None
                try:
                    cart_total = cart_item2.cart.total
                except:
                    cart_total = None
                try:
                    tax_total = cart_item2.cart.tax_total
                except:
                    tax_total = None
                try:
                    total_items = cart_item2.cart.items.count()
                except:
                    total_items = 0

                data = {
                    'cart_total': cart_total,
                    'deleted': delete_item,
                    'discount_total': discount_total,
                    'shipping_total': shipping_total,
                    'line_total': line_total,
                    'price': price,
                    'promo_code': promo_code,
                    'subtotal': subtotal,
                    'tax_total': tax_total,
                    'total_items': total_items,
                }

                return JsonResponse(data)

        # Shipping service list for context
        shipping_service_list = models.ShippingService.objects.active().order_by('id')

        # Recommended product list for context
        current_site = get_current_site(request)
        to_exclude_list = self.get_object().items.all()
        category1_count = self.get_object().items.filter(
            product__category=1
        ).count()
        if category1_count < 3:
            related_product_list1 = Product.objects.active().filter(
                sites=current_site.id,
                category=1
            ).exclude(variation__in=to_exclude_list).order_by('?')[:1]
        else:
            related_product_list1 = ''
        related_product_list2 = Product.objects.active().filter(
            sites=current_site.id,
            category=6
        ).exclude(variation__in=to_exclude_list).order_by('?')[:1]
        related_product_list3 = Product.objects.active().filter(
            sites=current_site.id,
            category=2
        ).exclude(variation__in=to_exclude_list).order_by('?')[:1]
        related_product_list = list(chain(
            related_product_list1,
            related_product_list2,
            related_product_list3
        ))
        context = {
            'object': self.get_object(),
            'product_list': related_product_list,

src/page/templates/page/cgv.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_f %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_g %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_t %}{{ seo.get_seo_title }}{% endblock %}

{% block seo_description %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_f %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_g %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_t %}{{ seo.get_seo_description }}{% endblock %}

{% block seo_image %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_f %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_g %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_t %}{{ seo.get_seo_image }}{% endblock %}

{% block content %}

<div class="cgv-page">
	<div class="container">
		<div>
			<h1 class="text-uppercase text-center t_text86"></h1>
			<h2 class="text-center t_text87"></h2>
		</div>
		<div>
			<div class="article_section t_text88"></div>
		</div>
		<a href="{% url 'page:home' %}" class="article_btn t_text89"></a>
	</div>
</div>

{% endblock %}

src/page/templates/page/home_capsulier.html
{% extends "base.html" %}

{% load static %}

{% block head_title %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_f %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_g %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_t %}{{ seo.get_seo_title }}{% endblock %}

{% block seo_description %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_f %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_g %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_t %}{{ seo.get_seo_description }}{% endblock %}

{% block seo_image %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_f %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_g %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_t %}{{ seo.get_seo_image }}{% endblock %}

{% block head_js %}
{% if not live_test %}
<script src="{% static 'bower_components/jquery.easing/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'page/js/home.js' %}"></script>
{% else %}
<script src="{% static 'vendor/jquery.easing/js/jquery.easing.min.js' %}"></script>
<script src="{% static 'page/dist/home.min.js' %}"></script>
{% endif %}
{% endblock %}

{% block content %}

<div class="home-page">

	<!-- Header Slider -->
	<div class="section1">
		<div id="header-slider" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner" role="listbox">
				{% for object in slider_list %}
				<div class="item {% if forloop.first %}active{% endif %}" style="background-image: url({{ object.get_image_hq }})">
					<div class="container">
						<div class="custom-carousel-caption">
							{% if object.title %}
							<hr>
							<h1 class="">{{ object.title }}</h1>
							{% endif %}
							{% if object.url %}
							<div>
								<a href="{{ object.url }}">{{ object.button_text }}</a>
							</div>
							<img src="" class="t_text228">
							{% endif %}
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<!-- Controls -->
			{% for object in slider_list %}
			{% if forloop.counter == 2 %}
			<a class="left carousel-control" href="#header-slider" role="button" data-slide="prev">
				<img src="{{ text229.get_image }}" alt="" class="left-arrow t_text229">
			</a>
			<a class="right carousel-control" href="#header-slider" role="button" data-slide="next">
				<img src="{{ text230.get_image }}" alt="" class="right-arrow t_text230">
			</a>
			{% endif %}
			{% endfor %}
			<div class="down-arrow">
				<p class="t_text96"></p>
				<a class="click" href="#section2"><img src="" alt="Click" class="t_text231"></a>
			</div>
		</div>
	</div>

	<!-- Capsules -->
	<div id="section2" class="section2">
		<div class="container block1">
			<div class="row t1_alpha align-items-center">
				<div class="col">
					<hr>
				</div>
				<div class="col-6">
					<h1 class="t_text99"></h1>
				</div>
				<div class="col">
					<hr>
				</div>
			</div>
			<div class="row">
				{% for object in capsule_list %}
				{% include "product/includes/product_block.html" with product=object col_class_set="col-md-4 col-sm-3" %}
				{% endfor %}
			</div>
		</div>
	</div>

	<!-- Others -->
	<div id="section3" class="section3">
		<div class="container block1">
			<div class="row t1_alpha align-items-center">
				<div class="col">
					<hr>
				</div>
				<div class="col-6">
					<h1 class="text-uppercase text-center t_text100"></h1>
				</div>
				<div class="col">
					<hr>
				</div>
			</div>
		</div>
		<div class="container block2">
			<div class="row zarmeur1">
				{% for object in other_list %}
				{% include "product/includes/product_block.html" with product=object col_class_set="col-md-2 col-sm-4 col-6" %}
				{% endfor %}
			</div>
			<div class="text-center mm_mt_20">
				<a href="{% url 'product:product_list' %}" class="cap_button t_text204"></a>
			</div>
			<div class="text-center mm_mt_20">
				<a href="#section4" class="click"><img src="" alt="" class="center-block t_text233"></a>
			</div>
		</div>
	</div>

	<!-- My Caps -->
	<div id="section4" class="section4 t_bg92" style="background-image: url('')">
		<div class="text-details">
			<h1 class="text-uppercase t_text93"></h1>
			<img src="" alt="" class="center-block t_text234">
			<div class="t_text94"></div>
			<!-- <div class="mycaps_btn"><a href="{% url 'mycaps:mycaps' %}" class="cap_button t_text95"></a></div> -->
		</div>
	</div>

	<!-- Blog -->
	<div class="section5">
		{% include "blog/includes/blog_list_block.html" with object_list=blog_list %}
	</div>

</div>

{% endblock %}

src/page/templates/page/home_conservatoire.html
{% extends "base.html" %}

{% load static %}
{% load text_extras %}

{% block head_title %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_f %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_g %}{{ seo.get_seo_title }}{% endblock %}
{% block head_title_t %}{{ seo.get_seo_title }}{% endblock %}

{% block seo_description %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_f %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_g %}{{ seo.get_seo_description }}{% endblock %}
{% block seo_description_t %}{{ seo.get_seo_description }}{% endblock %}

{% block seo_image %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_f %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_g %}{{ seo.get_seo_image }}{% endblock %}
{% block seo_image_t %}{{ seo.get_seo_image }}{% endblock %}

{% block content %}

<div class="home-conservatoire-page">

	<!-- Start main slider -->
	<div class="alfa1">
		<div id="mainSlider" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner" role="listbox">
				{% for object in slider_list %}
				<div class="item {% if forloop.first %}active{% endif %}">
					<img src="{{ object.get_image_hq }}" alt="">
					<div class="carousel-caption">
						{% if object.title %}
						<hr>
						<h1>{{ object.title }}</h1>
						{% endif %}
						{% if object.url %}
						<div class="slider_btn"><a href="{{ object.url }}">{{ object.button_text }}</a></div>
						<img src="{{ text238.get_image }}" class="button-rectangle">
						{% endif %}
					</div>
				</div>
				{% endfor %}
			</div>

			<!-- Controls -->
			{% for object in slider_list %}
			{% if forloop.counter == 2 %}
			<a class="left carousel-control" href="#mainSlider" role="button" data-slide="prev">
				<img src="{{ text239.get_image }}" alt="" class="left-arrow">
			</a>
			<a class="right carousel-control" href="#mainSlider" role="button" data-slide="next">
				<img src="{{ text240.get_image }}" alt="" class="right-arrow">
			</a>
			{% endif %}
			{% endfor %}
		</div>

		<div class="down-arrow">
			<p class="t_text241"></p>
			<a href="#section2"><img class="t_text242" src="" alt="Click"></a>
		</div>
	</div>
	<!-- End main slider -->

	<!-- Start Category -->
	<div class="alfa2">
		<div class="container">
			<div class="row no-gutters justify-content-center">
				{% for category in navbar_category_list %}
				<div class="col-lg-3 col-md-4 col-sm-6">
					<a class="bravo1" href="{{ category.get_absolute_url }}">
						<img src="{{ category.get_image_square_hq }}">
						<div class="charlie1">
							<h1 class="text-uppercase text-center">{{ category.title }}</h1>
							<p class="text-center">{{ category.description|truncatewords:6 }}</p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<!-- End category -->

	<!-- Start Map -->
	<div class="alfa3">
		<div class="bravo1 t_bg135" src="" alt=""></div>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="bravo2 text-center">
						<h1 class="t_text136"></h1>
						<hr>
						<p class="t_text137"></p>
						<a href="{% url 'page:map' %}" class="cap_button t_text138"></a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Map -->

	<!-- Start logo -->
	<div class="alfa4">
		<div class="bravo1">
			<img class="t_text139" src="">
		</div>
	</div>
	<!-- End logo -->

	<!-- Start call to action -->
	<div class="alfa5 t_bg143">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-7 col-md-10">
					<div class="bravo1">
						<h1 class="t_text140"></h1>
						<img class="t_text246" src="" alt="">
						<p class="t_text141"></p>
						<a href="" class="cap_button t_text142"></a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End call to action -->

	<!-- Start blog -->
	<div class="alfa6">
		{% include "blog/includes/blog_list_block.html" with object_list=blog_list %}
		<div class="d-flex justify-content-center">
			<a href="{% url 'blog:blog_list' %}" class="cap_button t_text144"></a>
		</div>
	</div>
	<!-- End blocg -->

</div>



<!-- googlemap -->
<script src="http://maps.googleapis.com/maps/api/js?key={{ GEOPOSITION_GOOGLE_MAPS_API_KEY }}"></script>
<script>
    function initialize() {
        var myLatLng = {lat: 48.842224, lng: 2.311086};

        var mapProp = {
            center:myLatLng,
            zoom:17,
            mapTypeId:google.maps.MapTypeId.ROADMAP,
            scrollwheel: false
        };
        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Le Capsulier!'
        });

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<script type="text/javascript">
	$('.down-arrow a').on('click', function (e) {
		e.preventDefault();

		var target = this.hash;
		var $target = $(target);

		$('html, body').stop().animate({
			'scrollTop': $target.offset().top-160
		}, 900, 'swing', function () {
			window.location.hash = target;
		});
	});
</script>

{% endblock %}

src/page/templates/page/pro.html
{% extends "base.html" %}

<div class="professional_page">
</div>